# MacNix Calamares Settings
---
modules-search: [ local, /usr/lib/calamares/modules ]

sequence:
  - show:
    - welcome
    - partition
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - macnix-welcome
    - macnix-gpu-detect
    - macnix-macos-fetch
    - macnix-macos-install
    - macnix-gpu-config
    - fstab
    - displaymanager
    - networkcfg
    - hwclock
    - bootloader
    - umount
  - show:
    - finished

branding: macnix

prompt-install: true
dont-chroot: false
