efi:
    mountPoint: "/boot/efi"
    recommendedSize: 512MiB
    minimumSize: 256MiB

defaultPartitionTableType: gpt
defaultFileSystemType: ext4

# Custom layout for "Erase disk" mode
partitionLayout:
    - name: "System"
      filesystem: ext4
      mountPoint: "/"
      size: 30GiB
    - name: "macOS Storage"
      filesystem: ext4
      mountPoint: "/var/lib/macnix"
      size: 100%

# Only show simplified modes
availableInstallTypes:
    - erase
    - alongside
